basePath: /
definitions:
  models.TodoList:
    properties:
      description:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
host: localhost:1323
info:
  contact: {}
  description: This is a sample server RestAPI server.
  title: Swagger RestAPI
  version: "2.0"
paths:
  /note:
    post:
      parameters:
      - description: Title
        in: path
        name: title
        required: true
        type: string
      - description: Description
        in: path
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TodoList'
      summary: Create note based on given ID
      tags:
      - note
  /note/:id:
    delete:
      parameters:
      - description: Note ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TodoList'
      summary: Delete note based on given ID
      tags:
      - note
    get:
      parameters:
      - description: Note ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TodoList'
      summary: Retrieves note based on given ID
      tags:
      - note
    put:
      parameters:
      - description: Title
        in: path
        name: title
        required: true
        type: string
      - description: Description
        in: path
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TodoList'
      summary: UpdateNote note based on given ID
      tags:
      - note
  /notes:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TodoList'
            type: array
      summary: GetAll note
      tags:
      - note
swagger: "2.0"
